export const MASTER_MODULES = [
  {
    id: "dashboard",
    icon: "◈",
    title: "GENEL BAKIŞ",
    short: "MASTER Dashboard",
    description:
      "Tüm DDPro operasyonlarını, canlı modülleri ve planlı alanları tek merkezden izle.",
    dataMode: "hybrid",
    availabilityLabel: "Merkez görünüm",
    statusTone: "silver",
    keywords: ["dashboard", "genel", "bakış", "merkez"],
  },
  {
    id: "projects",
    icon: "▣",
    title: "PROJELER",
    short: "Canlı API modülü",
    description:
      "Mevcut proje akışını koruyarak aktif kayıtları, yerel eklemeleri ve operasyon durumlarını yönet.",
    dataMode: "live",
    availabilityLabel: "Canlı veri uyumlu",
    statusTone: "emerald",
    keywords: ["proje", "project"],
  },
  {
    id: "research",
    icon: "⌕",
    title: "TEDARİK & ARAŞTIRMA",
    short: "Canlı API modülü",
    description:
      "Araştırma ve tedarik kayıtlarını mevcut backend uyumluluğunu bozmadan merkezi yapıda izle.",
    dataMode: "live",
    availabilityLabel: "Canlı veri uyumlu",
    statusTone: "emerald",
    keywords: ["araştırma", "research", "tedarik"],
  },
  {
    id: "offers",
    icon: "€",
    title: "TEKLİFLER",
    short: "Canlı API modülü",
    description:
      "Teklif listesi, detay paneli ve yerel taslak davranışını koruyarak teklif merkezini yönet.",
    dataMode: "live",
    availabilityLabel: "Canlı veri uyumlu",
    statusTone: "emerald",
    keywords: ["teklif", "offer"],
  },
  {
    id: "ai",
    icon: "✦",
    title: "DDPRO AI",
    short: "Yerel çalışma alanı",
    description:
      "AI çalışma alanı hazır; gelişmiş servis entegrasyonu henüz bağlı değil ve açıkça işaretlenir.",
    dataMode: "local",
    availabilityLabel: "Bağlantı bekleniyor",
    statusTone: "graphite",
    keywords: ["ai", "zeka", "analiz"],
  },
  {
    id: "crm",
    icon: "◎",
    title: "CRM",
    short: "Placeholder modül",
    description:
      "CRM yüzeyi hazırlanır; bu aşamada backend bağlantısı veya sahte veri gösterilmez.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["crm", "müşteri"],
  },
  {
    id: "calendar",
    icon: "◷",
    title: "TAKVİM",
    short: "Placeholder modül",
    description:
      "Takvim yerleşimi API entegrasyonuna hazırdır; planlı görünümde bağlantısız durum net belirtilir.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["takvim", "calendar"],
  },
  {
    id: "messages",
    icon: "✉",
    title: "MESAJLAR",
    short: "Placeholder modül",
    description:
      "Mesaj merkezi için kontrollü bir kabuk sunulur; tamamlanmamış işlevler gerçekmiş gibi gösterilmez.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["mesaj", "message", "chat"],
  },
  {
    id: "reports",
    icon: "▤",
    title: "RAPORLAR",
    short: "Placeholder modül",
    description:
      "Raporlar alanı gelecekteki veri bağlantıları için hazırlanır; bu sürümde yalnızca yapısal yer tutucu sunulur.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["rapor", "report"],
  },
  {
    id: "materials",
    icon: "⬡",
    title: "MALZEMELER",
    short: "Placeholder modül",
    description:
      "Malzeme yönetimi kabuğu oluşturulur; henüz bağlı olmayan katalog verileri taklit edilmez.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["malzeme", "material"],
  },
  {
    id: "suppliers",
    icon: "⛁",
    title: "TEDARİKÇİLER",
    short: "Placeholder modül",
    description:
      "Tedarikçi alanı API'ye hazır mimari sunar; sahte satıcı kayıtları üretilmez.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["tedarikçi", "supplier"],
  },
  {
    id: "documents",
    icon: "☰",
    title: "DOKÜMANLAR",
    short: "Placeholder modül",
    description:
      "Doküman merkezi yapısal olarak hazırdır; gerçek depolama bağlantısı gelene kadar boş durum gösterilir.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["doküman", "document", "evrak"],
  },
  {
    id: "systems",
    icon: "⚙",
    title: "SİSTEM",
    short: "Yerel yönetim modülü",
    description:
      "Merkezi hafıza, entegrasyon ve altyapı kartları mevcut yerel davranışlarla korunur.",
    dataMode: "local",
    availabilityLabel: "Yerel kontrol aktif",
    statusTone: "silver",
    keywords: ["sistem", "system", "hafıza", "entegrasyon"],
  },
  {
    id: "settings",
    icon: "⋯",
    title: "AYARLAR",
    short: "Placeholder modül",
    description:
      "Ayarlar modülü yerleşimi hazırlanır; yapılandırma API'si bağlanana kadar yalnızca yönlendirici kabuk sunulur.",
    dataMode: "placeholder",
    availabilityLabel: "Bağlantı hazır değil",
    statusTone: "graphite",
    keywords: ["ayar", "settings", "konfigürasyon"],
  },
];
