ALTER TABLE research_items
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS product TEXT,
  ADD COLUMN IF NOT EXISTS manufacturer TEXT,
  ADD COLUMN IF NOT EXISTS technical_info TEXT,
  ADD COLUMN IF NOT EXISTS price TEXT,
  ADD COLUMN IF NOT EXISTS price_verification TEXT NOT NULL DEFAULT 'Doğrulanmadı',
  ADD COLUMN IF NOT EXISTS url TEXT;
