ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS area_m2 NUMERIC CHECK (area_m2 IS NULL OR area_m2 >= 0),
  ADD COLUMN IF NOT EXISTS systems JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
